##spring:
##  application:
##  name: backend
##
##datasource:
##  url: jdbc:mysql://localhost:3306/skillgappro
##  username: root
##  password: Amo@1234
##  driver-class-name: com.mysql.cj.jdbc.Driver
##
##
##jpa:
##  hibernate:
##  ddl-auto: update
##  show-sql: true
##
##cloudinary:
##  cloud_name: de28xnvlv
##  api_key: 431951741465886
##  api_secret: 3TLJaSzxD3kROmw7J3Pc7tyIZas
##
##
##
##razorpay:
##  key: rzp_test_Sd71PDsZvJ4qeD
##  secret: nd9W08Lu59WQJpCFL5FbQ2KF
##
##
##  servlet:
##    multipart:
##    max-file-size: 10MB
##    max-request-size: 10MB
#
#spring:
#  application:
#    name: backend
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/skillgappro
#    username: root
#    password: Amo@1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#

#
#razorpay:
#  String secret = ""; // ✅ ONLY SECRET
#  key:


#server:
#  port: 8080
#
#spring:
#  application:
#    name: skillgappro-backend
#
#datasource:
#  url: jdbc:mysql://localhost:3306/skillgappro
#  username: root
#  password: Amo@1234
#  driver-class-name: com.mysql.cj.jdbc.Driver
#
#jpa:
#  hibernate:
#    ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
## ✅ Razorpay Config (IMPORTANT)
#razorpay:
#  key-id: rzp_live_SeeOC5bovL3HOm
#  key-secret: Y0gU0AV1jFbhIL3TqO6txTxo
#
## ✅ CORS (optional if using config class)
#cors:
#  allowed-origins: http://localhost:5173
#
#  # cloudinary
#cloudinary:
#  cloud_name: de28xnvlv
#  api_key: 431951741465886
#  api_secret: 3TLJaSzxD3kROmw7J3Pc7tyIZas

server:
  port: 8080

spring:
  application:
    name: skillgappro-backend

  datasource:
    url: jdbc:mysql://localhost:3306/skillgappro
    username: root
    password: Amo@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Razorpay
razorpay:
  key: rzp_live_Sfggxgpx4gKU9v
  secret: xfa2233xozIBXDjzr1oPWAHT

# CORS
cors:
  allowed-origins: http://localhost:5173

# Cloudinary
cloudinary:
  cloud_name: de28xnvlv
  api_key: 431951741465886
  api_secret: 3TLJaSzxD3kROmw7J3Pc7tyIZas